# Generated by Django 4.1.3 on 2022-12-25 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('rate', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('price', models.BigIntegerField()),
                ('room_num', models.SmallIntegerField()),
                ('passenger_num', models.SmallIntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='room/images/')),
                ('is_booked', models.BooleanField(default=False)),
                ('checkin', models.BooleanField(default=False)),
                ('checkout', models.BooleanField(default=False)),
                ('facility', models.CharField(choices=[('1', 'parking'), ('2', 'breakfast'), ('3', 'fitness center'), ('4', 'free wifi')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
