# Generated by Django 4.1.3 on 2023-01-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_rename_roomreservation_hotelroomreservation'),
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='HotelRoom',
        ),
    ]
