# Generated by Django 4.1.3 on 2023-01-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rate',
            field=models.CharField(choices=[('one_star', '1_star'), ('two_star', '2_star'), ('three_star', '3_star'), ('four_star', '4_star'), ('five_star', '5_star')], max_length=30),
        ),
    ]
