# Generated by Django 4.1.3 on 2023-01-01 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='residence/images/'),
        ),
    ]
