# Generated by Django 4.1.3 on 2023-01-03 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractResidenceReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_choices', models.CharField(choices=[('canceled', 'canceled'), ('reserved', 'reserved')], max_length=20)),
                ('reservation_time', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('total_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('abstractresidencereservation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book.abstractresidencereservation')),
                ('is_valid', models.BooleanField(default=True)),
            ],
            bases=('book.abstractresidencereservation',),
        ),
        migrations.CreateModel(
            name='AirplaneReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_choices', models.CharField(choices=[('canceled', 'canceled'), ('reserved', 'reserved')], max_length=20)),
                ('reservation_time', models.DateTimeField()),
                ('total_price', models.IntegerField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportations.airplane')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
