# Generated by Django 4.1.3 on 2023-01-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0001_initial'),
        ('reservation', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomReservation',
            new_name='HotelRoomReservation',
        ),
    ]
